"""Command-line interface for log ingestion."""

from pathlib import Path
import argparse
from datetime import datetime

from app.detection.engine import DetectionEngine
from app.detection.rules.directory_scanning import DirectoryScanningRule
from app.detection.rules.excessive_sudo import ExcessiveSudoRule
from app.detection.rules.new_user_creation import NewUserCreationRule
from app.detection.rules.sql_injection import SQLInjectionRule
from app.detection.rules.ssh_brute_force import SSHBruteForceRule
from app.detection.rules.successful_after_failures import SuccessfulAfterFailuresRule
from app.detection.rules.suspicious_user_agent import SuspiciousUserAgentRule
from app.detection.rules.xss_attempt import XSSAttemptRule
from app.services.ingestion import IngestionResult, ingest_logs

def build_engine() -> DetectionEngine:
    """Create an engine with all eight detection rules."""

    engine = DetectionEngine()

    engine.register_rule(SSHBruteForceRule())
    engine.register_rule(SuccessfulAfterFailuresRule())
    engine.register_rule(ExcessiveSudoRule())
    engine.register_rule(NewUserCreationRule())
    engine.register_rule(DirectoryScanningRule())
    engine.register_rule(SQLInjectionRule())
    engine.register_rule(XSSAttemptRule())
    engine.register_rule(SuspiciousUserAgentRule())

    return engine

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description="Ingest authentication and access logs."
    )

    parser.add_argument(
        "--auth-log",
        help="Path to the Linux authentication log.",
    )

    parser.add_argument(
        "--access-log",
        help="Path to the Apache access log.",
    )

    args = parser.parse_args()

    if args.auth_log is None and args.access_log is None:
        parser.error(
            "at least one of --auth-log or --access-log is required"
        )
    return args

def print_summary(result: IngestionResult) -> None:
    """Print a readable ingestion summary."""

    print("\nINGESTION SUMMARY")
    print("=" * 50)

    print(
        f"Auth events processed: {result.auth_lines_processed}"
    )
    print(
        f"Access events processed: {result.access_lines_processed}"
    )
    print("\nAlerts generated by rule:")

    if result.alerts_by_rule:
        for rule_name, count in sorted(result.alerts_by_rule.items()):
            print(f"    {rule_name:<30} {count}")
    else:
        print(" None")

    print("\nTotals")
    print("=" * 50)
    print(f"Alerts generated:       {result.alerts_generated}")
    print(f"Alerts saved to DB:     {result.alerts_saved}")

def main() -> None:
    """Run the CLI ingestion pipeline."""

    args = parse_args()

    if args.auth_log is not None and not Path(args.auth_log).is_file():
        print(f"Error: auth log file not found: {args.auth_log}")
        return

    if args.access_log is not None and not Path(args.access_log).is_file():
        print(f"Error: access log file not found: {args.access_log}")
        return

    result = ingest_logs(
        auth_log_path=args.auth_log,
        access_log_path=args.access_log,
        engine=build_engine(),
        reference_date=datetime.now(),
    )

    print_summary(result)

if __name__ == "__main__":
    main()